### ISSUE TITLE
Info about showing the network requests.

### ISSUE THREAD

**Issue by cool-dev-guy** [vikiival/vercelgl#10]
Hi thanks for this amazing project @vikiival,
I was trying to access the requests that are being send in the page,and i could get the requesting urls,but is there any way that i can get the response data ?
```
page.on('request', (request) => {
    console.log(request.url()); 
    request.continue(); 
  });
```
This can be used to get the requests,but the response data is `null` when i try to do it,is there any way to do this?

**Comment by vikiival** [comment]
> This can be used to get the requests,but the response data is `null` when i try to do it,is there any way to do this?

Hello, 
I honestly do not know. 

But my advice is to setup a basic pupeteer project, so you can test it locally.
Moreover ChatGPT or other LLM model can be your friend to consult

**Comment by cool-dev-guy** [comment]
Oh thanks
