### ISSUE TITLE
encountering a problem, ask for a solution.

### ISSUE THREAD

**Issue by jiangxiaoyu66** [vikiival/vercelgl#9]
When I was calling the service of your example, I encountered the following error. I don't know how to solve it. Ask for help![image](https://github.com/vikiival/vercelgl/assets/32289005/5bd9059b-bb8d-4fbc-82c0-4d5a86dcb65a)

**Comment by vikiival** [comment]
Hello, please do deploy your function with Vercel Premium, you can then set the limit, see #8

**Comment by vikiival** [comment]
Updated readme in a39e1d7ee937d7c0c74be1b8e4c3d71347b3a655
